### ISSUE TITLE
Broken HTML signature Mail 5.1.3 links and images not working

### ISSUE THREAD

**Issue by PeopleInside** [nextcloud/mail#11261]
### Steps to reproduce

1. go to an HTML editor that convert HTML source to a visual signature (as badly Mail doesn't support HTML source edit or input); you can use https://htmledit.squarefree.com/ or https://onlinehtmleditor.dev/

The HTML source of the signature you need to test is:

```
<a href="https://demo.livehelperchat.com" target="_blank" rel="noopener noreferrer">
  <img 
    src="https://demo.livehelperchat.com/site_admin/restapi/onlineimage?&online=I'm%20online&offline=I'm%20offline&w=200" 
    alt="Chatta con noi"
    style="display: block; margin: 0 auto; cursor: pointer;" />
</a>
```
The result will be an image that is clickable (that has a link that open if clicked):

![Image](https://github.com/user-attachments/assets/891aaefc-dc5c-43ef-8784-27a956d394ba)

2. copy this signature into Mail app
3. Send an email and you will see that the image has no link and maybe is also not aligned on the center
Also if you try to insert a link in this image in the editor on Mail signature editor page you can't

### Expected behavior

Pasted signature should work as expected as in the external editor so the result for the example above should be an image that is centred, clickable and that open a link

### Actual behavior

In the signature editor if you paste the signature above you cannot insert a link because all editor button are disabled.

![Image](https://github.com/user-attachments/assets/c9c631a0-4ec1-477a-8607-d4be6a04a399)

So two issues: pasted HTML signature is pasted broken with the image that miss a link.
Also if is showed centred will be not centred when email is sent and link is missing. Also in the editor is no more possibile use the link button to add a link as showed in the above screenshot 

### Mail app version

5.1.3

### Nextcloud version

3.1.0.5

### Mailserver or service

personal one custom domain

### Operating system

Ubuntu 22.04.5 LTS

### PHP engine version

Other

### Web server

Other

### Database

MariaDB

### Additional info

https://github.com/nextcloud/mail/issues/11260#issuecomment-2965552441

**Comment by ChristophWurst** [comment]
Thank you for your report. 

The broken image should be fixed once we have external images support. It's possibly coming with https://github.com/nextcloud/mail/pull/11160.

**Comment by PeopleInside** [comment]
Hi, how are you? I hope you are well.
I tested Mail version 5.3.1 and I confirm the issue with the script inclusion in HTML email still not working correctly.
The Live Chat Button is not centred and miss the link.

It will be useful also have a source HTML button to edit the source.

**Comment by ChristophWurst** [comment]
> It will be useful also have a source HTML button to edit the source.

Tracked in https://github.com/nextcloud/mail/issues/11309

**Comment by PeopleInside** [comment]
The HTML signature and edit on email still be broken also on the latest Mail Version. I'm happy to see this issue still be opened so you know the issue still be not resolved.

My HTML signature pasted and saved into Mail loose image alignment, images sometimes are not showed. Still see a broken HTML interpreter that I hope will be fixed in the future.  

I'm happy a HTML source button has been added on signature and also on email composing.
Now should just fixed the fact HTML are not managed correctly 😊
