### ISSUE TITLE
Notification »Message flag could not be set«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#121]
Sometimes after restarting the browser or refreshing the view I get this notification. It’s a very technical message and isn’t really helpful, so it’s probably better to not show it at all.

(I assume what is meant is the read/unread »flag« in this case?)

**Comment by ChristophWurst** [comment]
It should only be shown if the user actively changed a flag (e.g. flag a message or mark as unread). If it's done automatically we should not show a notification in case of an error

**Comment by jancborchardt** [comment]
And then, we should use more specific and less technical wording:

> Error while marking message unread :-/

> Couldn't favorite that message :'-( (or unfavorite, depending)

**Comment by ChristophWurst** [comment]
Yup, most important change is to add smileys 😆

**Comment by jancborchardt** [comment]
;D as usual

**Comment by Huster-at-github** [comment]
Here it's shown every time I switch from one unread e-mail to the next. And all e-mails are marked as "Unread" although I read them.

**Comment by ChristophWurst** [comment]
IMO mostly fixed now that we have proper background sync (no more messages that have been deleted on other devices/tabs) and browser reloading issues #322 have been resolved.

**Comment by jancborchardt** [comment]
I still get this often after resume from suspend and such, with current master. Especially when there's new messages loaded.

**Comment by ChristophWurst** [comment]
> I still get this often after resume from suspend and such, with current master. Especially when there's new messages loaded.

You sure? With the very latest master of both this app an server? If so, please provide more information, e.g. browser logs, nextcloud.log and such. That could be a CSRF issue.

**Comment by ChristophWurst** [comment]
> With the very latest master of both this app an server?

Server PR was merged 5d ago https://github.com/nextcloud/server/pull/6360

**Comment by jancborchardt** [comment]
I'll make sure to update again and monitor it. Had it this morning but might have been an older version of either server or Mail.

**Comment by jancborchardt** [comment]
Aaand just got it again after a suspend:
![screenshot from 2017-09-12 23-18-50](https://user-images.githubusercontent.com/925062/30348776-d6cc6e0c-9810-11e7-8b67-bb591d528bc0.png)

**Comment by jancborchardt** [comment]
On clicking a new (unread) message which had been loaded in the background.

**Comment by ChristophWurst** [comment]
well, how about you *really* use our current master? That `SHOW` log indicates that you're on a older commit because #506 removed that 😉 

Would be great to also see the network log. Did you have access to the internet to connect to your cloud? What's the HTTP status code? What does the response look like?

**Comment by jancborchardt** [comment]
Aaah, that's because I was on the refactor branch of the autoconfig! :)

**Comment by jancborchardt** [comment]
Just happened again, here’s the browser log:
![screenshot from 2017-09-14 15-17-17](https://user-images.githubusercontent.com/925062/30431755-f11a777c-995f-11e7-9b89-37340bb95b09.png)


And the network log, CSRF error:
![screenshot from 2017-09-14 15-19-03](https://user-images.githubusercontent.com/925062/30431804-16723960-9960-11e7-82bb-1c004532a801.png)


No nextcloud.log error.

**Comment by ChristophWurst** [comment]
Closing as that error originates from the previous front-end code.
