### ISSUE TITLE
Cannot open parent folder, subfolders are expanded instead

### ISSUE THREAD

**Issue by reuterbal** [nextcloud/mail#2050]
### Expected behavior
Imagine a folder structure like this
```
--+-- ParentA
  |-- ParentA.SubA
  |-- ParentA.SubB
----- ParentB
```
1. Clicking on `ParentA` opens the message list in that folder
2. Clicking on the "Expansion triangle" in front of `ParentA` expands the list of subfolders
3. Clicking on `ParentA.SubA` opens the message list in that subfolder
4. Clicking on `ParentB` (without subfolders) opens the message list in that folder

### Actual behavior
1. Clicking on `ParentA` expands the list of subfolders, message list is not shown
2. Clicking on the "Expansion triangle" in front of `ParentA` expands the list of subfolders
3. Clicking on `ParentA.SubA` opens the message list in that subfolder
4. Clicking on `ParentB` (without subfolders) opens the message list in that folder

I.e., Parent folders with subfolders cannot be opened, all other situations work fine.

### Mail app

**Mail app version:** 0.17.0

**Mailserver or service:** Dovecot and 1&1

### Server configuration

**Operating system**: Ubuntu 18.04.3

**Web server:** Apache 2.4.29-1ubuntu4.11

**Database:** MySQL 5.7.27-0ubuntu0.18.04.1

**PHP version:** 7.2.19-0ubuntu0.18.04.2

**Nextcloud Version:** 16.0.4, 16.0.5

#### Client configuration
**Browser:** Firefox 61.0.2

**Operating system:** Ubuntu 18.04.3, openSUSE Leap 42.3

**Comment by ChristophWurst** [comment]
>     1. Clicking on `ParentA` expands the list of subfolders, message list is not shown

Does the URL change in that step? Could you inspect the href on the list item?

**Comment by reuterbal** [comment]
The URL stays the same, however href seems to be correct: I can right-click and "Open in a new tab" which yields the message list.

**Comment by VinceMasuka** [comment]
I'm experiencing the same issue over here:

- If a folder has sub folders, the content of parent folder is just not shown.
- URL does not change in this step. Only the very last folder will show content (having the URL changing).
- Folders with no subfolders change URL and work flawlessly in listing

This is what href looks like on the inbox folder (containing a favorites folder):
`<a href="/apps/mail/#/accounts/4/folders/SU5CT1g=" class="icon-inbox">
		Posteingang
	</a>`


> The URL stays the same, however href seems to be correct: I can right-click and "Open in a new tab" which yields the message list.
I can confirm that this workaround actually works. Thanks!

Anyway, I hope we can get a real solution to this matter...

**Comment by yafp** [comment]
Same Mail version (0.17.0), same nextcloud version (16.0.5) -> same issue. 

Open in a new window/tab is in fact a working workaround, but far from perfect.

Anything else you might need to debug this issue?

**Comment by ChristophWurst** [comment]
> Anything else you might need to debug this issue?

Time. I'll try to allocate some this week, but there is a lot on my plate right now. If any dev has time to take a deeper look I'd be very thankful :heart:

**Comment by VinceMasuka** [comment]
I also recognized, that if you click the mail icon on the very to menu of Nextcloud, it indeed opens the inbox you opened the very last time and shows all mails of the inbox correctly. That behavior is re-producable (just click on a random icon like "files" and back to "mail).

**Comment by nickvergessen** [comment]
I'm havin gthe same issue on my instance using 0.17.0, but it works find on my dev instance with master.

**Comment by ChristophWurst** [comment]
Tested with the help of a test account from @nickvergessen and we found out that this was fixed recently. Latest master does not have this problem anymore and the latest stable releases for Nextcloud 17 should also be fine :)

**Comment by reuterbal** [comment]
Sorry to bother again: I updated to NC 17.0.0 and the problem still persists with Mail 0.17.0. Thus, the latest stable doesn't seem to have the fix, yet.

**Comment by ChristophWurst** [comment]
Okay, then sorry for the confusion. Master will be released today most likely, so the fix will follow shortly :)

**Comment by reuterbal** [comment]
Can confirm: After update to 0.18.0, the issue is gone. Many thanks!

**Comment by ChristophWurst** [comment]
Awesome! Thanks for the feedback!
