### ISSUE TITLE
Make E-mail signatures HTML friendly

### ISSUE THREAD

**Issue by Jouwhost** [nextcloud/mail#2263]
### Feature Request

At the moment it's impossible to add html to a signature.
This means no image, urls etc.
This is a problem for users that expect more from an email client.

#### Summary

I would like to see any form of implementation where people can use the signature field with html.
I could easily work with plain text / html directly in the field.
Ofcourse an editor overtime would be great but i rather have HTML support the hard way next month, then a nice editor next year.

**Comment by el3ctrician** [comment]
I think adding image would be a nice feature to have

**Comment by ChristophWurst** [comment]
> At the moment it's impossible to add html to a signature.

#2191 :)

Why we don't want to allow arbitrary HTML: we still have to load it into the editor when the message is composed. And a sane editor (as we use it) will remove elements it doesn't know. Both because it simply can't work with them but also for security reasons. Thus we "just" have to add image support to our editor and this will work. You should be able to add links already.

**Comment by hanserasmus** [comment]
Hi @ChristophWurst, This is indeed good news that there is movement. Do you have any idea when an image/logo support will be available? Is it on any roadmap yet? There are some people requesting it.

**Comment by ChristophWurst** [comment]
For image support we'd have to check how feasible that is. The editor we use has support for that already, but you need to implement a back-end to store the files. In our case that would be some temporary local storage on the server, quite similar to the attachments feature we have.

I can't give you an ETA right now.

**Comment by somombo** [comment]
My dream is anything like a generated signature copied from a site like https://www.mail-signatures.com/signature-generator/#/pad-box

Should just magically appear correctly when pasted in our rich text editor, the same way it does when it's pasted into say, Gmail

**Comment by ChristophWurst** [comment]
> Should just magically appear correctly when pasted in our rich text editor, the same way it does when it's pasted into say, Gmail

Yes and no. You *can* paste HTML in the signature field. But the editor will strip anything that it doesn't know. Hence the result will be subpar.

I'm fine with gradually allowing more HTML formatting options in our editor. They just have to be enabled. And someone needs to test them with all of our feature to see if they work as expected in all scenarios.

**Comment by hanserasmus** [comment]
@Christoph this is a pressing matter wit my users. Will bounty help? I will
test it gladly and quickly for you! If the prospect is there that it qould
be implemented sooner rather than later.

**Comment by ChristophWurst** [comment]
I'll have a look at the formatting options. Then we can evaluate how much effort each of them takes to add. Images is most likely a big one. But others should be more easy to enable.

**Comment by hanserasmus** [comment]
OK cool! Thank you!

**Comment by jancborchardt** [comment]
The main part of this is fixed through **Allow HTML signatures #2191**. It would be less confusing if "Ability to add images to signatures" is a separate new issue, right?

**Comment by edosmedia** [comment]
Hello I love nextcloud but I cannot implement a signature in html when it could be possible, since this gives a lot of precency to the world

**Comment by carloscortesp** [comment]
This thread starts in the year 2019 and today, the year 2022, Nextcloud still does not allow HTML in the signature?

The signature we currently have in Gmail helps us plant efficient mental images of the type of company we are.

A plain text signature makes us look very bad as a company.

**Comment by ChristophWurst** [comment]
@carloscortesp feel free to read up on https://github.com/nextcloud/mail/issues/2733. It's unfortunately not as trivial as it seems. But if you are interested and capable of adding this feature I'm more than happy to assist you.
