### ISSUE TITLE
Cannot add recipients

### ISSUE THREAD

**Issue by republicus** [nextcloud/mail#2508]
This bug makes Nextcloud Mail nearly unusable from within Nextcloud.
I noticed the latest comment at the App Store is the same complaint.

### Expected behavior
Entering recipients' address into **To:** field adds recipients' email.

### Actual behavior
**Intermittently** (frequently) it becomes impossible to add recipients.
1. Typing the address may return no results or blank results -- leaving no option to add recipient.
2. Address not in contacts or previously used _may_ not be added.

![image](https://user-images.githubusercontent.com/47370709/72673357-501e5980-3a37-11ea-9a42-0b611dfb3f14.png)

It should be possible to enter text without engaging the mouse to add a recipient.
Currently even when it does behave - I must still click the **+**  button to add a recipient; or removing the **check** icon to remove a recipient.

Behavior like adding tags may be ideal where pressing Comma, Semicolon, Tab, and/or Return should add the address.

The current behavior is quite intermittent and annoying. I would even prefer a free form where email is consistently able to be sent.

### Mail app

**Mail app version:** 1.0.0
**Mailserver or service:** Postfix/Dovecot

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Chrome 74.0.3729.169
**Operating system:** Windows 10

**Comment by DecaTec** [comment]
Same here: When trying to set the recipient's mail address, it often let's you type some letters, but then the whole auto completion of the mail address seems to be broken.

Some more information from the browser's developer console:

```
TypeError: "t.customLabel(...) is null"
    optionKeys https://mydomain.de/apps/mail/js/mail.7.2cef98fdf1f1cf7cca86.js:391
    optionKeys https://mydomain.de/apps/mail/js/mail.7.2cef98fdf1f1cf7cca86.js:391
    get https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    evaluate https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    _n https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    isExistingOption https://mydomain.de/apps/mail/js/mail.7.2cef98fdf1f1cf7cca86.js:391
    filteredOptions https://mydomain.de/apps/mail/js/mail.7.2cef98fdf1f1cf7cca86.js:391
    get https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    evaluate https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    _n https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    render https://mydomain.de/apps/mail/js/mail.7.2cef98fdf1f1cf7cca86.js:391
    _render https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    r https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    get https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    run https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    pn https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    ee https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
    Yt https://mydomain.de/apps/mail/js/mail.js?v=3e3e5628-9:7
mail.js:7:11644
```
It's a pity, because it renders the mail app more ore less useless (or you need patience in order to write a simple mail).

**Comment by jancborchardt** [comment]
Can confirm, the "To" dropdown is quite confusing and doesn’t really work with keyboard only, like pressing enter.

@GretaD this is one for polishing the email writing flow. :)

**Comment by laurentiu2** [comment]
> **Intermittently** (frequently) it becomes impossible to add recipients.

Same here. 

Mail app
Mail app version: 0.17
Mailserver or service: Hetzner

Server configuration
Operating system: Ubuntu 18.0.4
Web server: Apache
Database: MariaDB
PHP version: PHP 7.3.13
Nextcloud Version: 16.0.7

Client configuration
Browser: Firefox 72.0.1
Operating system: Mac OS Catalina 10.15.2

**Comment by jdaviescoates** [comment]
Same here using NextCloud Mail hosted on Cloudron :(

It made me immediately rule out using it which is a shame because if you get label based folder management (like Gmail) sorted this'll possibly be better than Rainloop or Roundcube which seem like the only other options at present.

**Comment by ChristophWurst** [comment]
Ugh this is such a pain. @nextcloud/mail anyone ever able to reproduce? :cry:

**Comment by ChristophWurst** [comment]
(there is also another very similar ticket)

**Comment by laurentiu2** [comment]
#1863 this one?

**Comment by ChristophWurst** [comment]
Kind of. So there is even a third :wink:

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/issues/1973 :)

**Comment by republicus** [comment]
I believe this is <=NC 17 problem (I have none running < NC 17).
NC 18 dev install has not yet run into any of these problems.

The NC 18 server is an exact clone of my NC 17 machine, only updated to NC 18.

**Comment by ChristophWurst** [comment]
> I believe this is <=NC 17 problem (I have none running < NC 17).

Can anyone confirm? The latest Mail is currently supporting 17 and 18, which means they get all the updates of the libraries we use. Chances are this has been fixed upstream in the multiselect component and thus 17+ are not affected anymore? Just a wild guess.

**Comment by ChristophWurst** [comment]
On https://help.nextcloud.com/t/mail-app-sending-mail-hangs-in-chromium/66006/14 I read this can be narrowed down to be a problem with Chromium but not Chrome.

**Comment by jdaviescoates** [comment]
> > I believe this is <=NC 17 problem (I have none running < NC 17).
> 
> Can anyone confirm? The latest Mail is currently supporting 17 and 18, which means they get all the updates of the libraries we use. Chances are this has been fixed upstream in the multiselect component and thus 17+ are not affected anymore? Just a wild guess.

My [Cloudron](https://cloudron.io)-powered Nextcloud has recently been upgraded to NC18 and it does appear to have fixed this issue.  Still not the most intuitive UX (normally just tabbing, or writing a comma is enough), but at least it seems to work now!

**Comment by ChristophWurst** [comment]
>  Still not the most intuitive UX (normally just tabbing, or writing a comma is enough), but at least it seems to work now!

Unfortunately [not implemented yet upstream](https://github.com/shentao/vue-multiselect/issues/575), but I really like the idea!

**Comment by jdaviescoates** [comment]
@ChristophWurst please excuse my ignorance, but how is vue-multiselect connected to/ upstream to Nextcloud Mail? I guess Nextcloud Mail incorporates it somehow? Thanks!

**Comment by ChristophWurst** [comment]
Yes. We use https://github.com/nextcloud/nextcloud-vue for most components and the Multiselect is used for the recipient selection.

**Comment by ahstro** [comment]
We might have a fix for this in #2703. If anyone who has experienced it knows how to test code, that might confirm the hunch 😇

**Comment by ahstro** [comment]
Closing this as fixed in #2703. If it happens to anyone again, shout at me 🙇
