### ISSUE TITLE
Mail layout div quite small

### ISSUE THREAD

**Issue by DorianVasco** [nextcloud/mail#2870]
### Expected behavior
The content window of the selected mail should resize responsively to the browser size.

### Actual behavior
![Untitled-1](https://user-images.githubusercontent.com/6312198/78542220-26373080-77f7-11ea-9a19-5caf112a4796.png)
The width and height of the content window are quite contrained to a small size.

### Mail app

**Mail app version:** 1.1.4

**Mailserver or service:** self hosted / postfix / dovecot

### Server configuration

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Firefox 74

**Comment by jancborchardt** [comment]
The height issue is fixed with https://github.com/nextcloud/mail/pull/2222 and will be in the next release. :)

The width is a design decision as per https://github.com/nextcloud/mail/pull/2429#issuecomment-571901535
> The _width_ restriction is indeed intentional, as per https://github.com/nextcloud/mail/pull/2180
> Further reading on the cognitive science basis on that at https://en.wikipedia.org/wiki/Line_length

----------------------

What we could indeed improve is the way that HTML mails with such an extra container (the grey space) are handled. Not sure if this is possible at all though – @DorianVasco @nextcloud/mail any idea?

**Comment by ngaggi** [comment]
Same with v1.3.0 Beta 2 and Beta 3.

**Comment by jancborchardt** [comment]
@ngaggi what’s the same? The height should have been fixed. For the width, see my comment.

**Comment by ngaggi** [comment]
Sorry, mean the width issue.

**Comment by icewind1991** [comment]
The height is still an issue with 1.5.0

![image](https://user-images.githubusercontent.com/1283854/95352379-b7c05180-08b1-11eb-8d56-80f19acd310e.png)

**Comment by ChristophWurst** [comment]
We're running in circles but let me explain one more time: it's technically not possible to have an iframe auto-adjust its height. The only way to do this is by injecting javascript into the iframe, but since we show potentially dangerous content, we have our iframe run in sandbox mode, so no javascript is allowed. This make it impossible to apply this trick.

If one day there is a css/html/whatever change that allows the automagic resizing of iframes (with changing height as images load and all the other edge cases) we might be more lucky. But until then I see no technical solution.

If you know a trick, tho, let us know :pray:

**Comment by icewind1991** [comment]
you can have the iframe adjust to it's containers height though

**Comment by ChristophWurst** [comment]
Mind sharing more info or a guide explaining this?

**Comment by crdxfire** [comment]
@ChristophWurst Yesterday I upgrade to nc20, mail v1.5.0. we've discussed this already months ago and after an update back then, mail display was absolutely ok. for some reason with the update yesterday html content is now only displayed roughly only ~300px high. What happened!?

**Comment by ChristophWurst** [comment]
Threading happened. We could previous work around the problem by giving the message as much space as it needed without caring about any overflow on the button (hence a floating attachments icon). It was never a real solution but more of a workaround. Now that we have threads and very likely content below a message we have to prevent the overflow again.

That is why we have this *regression*.

We're not breaking this just for fun.

**Comment by st3iny** [comment]
Resolved by #3904
