### ISSUE TITLE
Server Erorr message when sending emails

### ISSUE THREAD

**Issue by g4jsg** [nextcloud/mail#296]
### Steps to reproduce
1. Create/forward/reply and enter your recipeints, subject & message, click send.
2. Message top center of screen says "Server error", message stays on editing screen
3. Email still was sent though, but doesn't show this in the Mail app side.

### Expected behaviour
Email shoudl send and save the sent email in the Sent folder.

### Actual behaviour
Stays in editing window, sends email but doesn't seem to know it has.

### Mail app

**Mail app version:** 
 Mail 0.6.2

**Mailserver or service:** 
Outlook, Hotmail, imap server.

**Transport security - IMAP:**
Auto setup, manual setup with or without ssl, tls, none all show same fault

**Transport security - SMTP:**
as above

**Number of accounts:**
8
**Mail app version build date:** (only if you are using a Nightly Build)
NA

### Server configuration
**Operating system**:
Ubuntu 16.4
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
Tried from 5.6 up to 7
**Version:** (see admin page)
11.0.1 (stable)
**Updated from an older version or fresh install:**
Fresh install
**List of activated apps:**
 Activity 2.4.1
 Collaborative tags 1.1.3
 Comments 1.1.0
 Default encryption module 1.4.1
 Deleted files 1.1.0
 File sharing 1.1.1
 First run wizard 2.0
 Gallery 16.0.0
 Log Reader 2.0.0
 Notifications 1.0.1
 Password policy 1.1.0
 PDF viewer 1.0.1
 Server info 1.1.1
 Share by mail 1.0.1
 Text editor 2.2
 Theming 1.1.1
 Update notification 1.1.1
 Versions 1.4.0
 Video player 1.0.0
 Collabora Online 1.1.25
 Mail 0.6.2
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**
Tried IE, Chrome, Firefox, Edge
**Operating system:**
Windows 8, 7, 10 and Max Sierra
##### Web server error log
```
Insert your webserver log here
```
Error	mail	Sending mail failed: Error when communicating with the server.	2017-01-25T12:08:23+0000
Error	mail	Sending mail failed: Server requires authentication.	2017-01-25T12:03:19+0000
Error	mail	Sending mail failed: Server requires authentication.	2017-01-25T12:02:55+0000
Error	mail	Sending mail failed: Server requires authentication.	2017-01-25T12:02:35+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:53+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:53+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:53+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:52+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:52+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:51+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:51+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:51+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:51+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:50+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:50+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:49+0000
Error	index	ParseError: syntax error, unexpected '<', expecting end of file	2017-01-25T12:01:47+0000
Error	mail	Sending mail failed: Error when communicating with the server.
##### Server log (data/nextcloud.log)
<details>
{"reqId":"Mp7SKNpKW3kY8SUOOLa4","remoteAddr":"109.121.29.93","app":"PHP","message":"file_get_contents(\/var\/www\/vhosts\/turing.xlcloud.uk\/httpdocs\/.htaccess): failed to open stream: No such file or directory at \/var\/www\/vhosts\/turing.xlcloud.uk\/httpdocs\/lib\/private\/Setup.php#434","level":3,"time":"2017-01-29T10:36:30+00:00","method":"POST","url":"\/index.php","user":"--","version":"11.0.1.2"}
{"reqId":"Mp7SKNpKW3kY8SUOOLa4","remoteAddr":"109.121.29.93","app":"PHP","message":"copy(\/var\/www\/vhosts\/turing.xlcloud.uk\/httpdocs\/.user.ini): failed to open stream: No such file or directory at \/var\/www\/vhosts\/turing.xlcloud.uk\/httpdocs\/lib\/private\/IntegrityCheck\/Checker.php#196","level":3,"time":"2017-01-29T10:36:48+00:00","method":"POST","url":"\/index.php","user":"oktogo","version":"11.0.1.2"}
{"reqId":"Mp7SKNpKW3kY8SUOOLa4","remoteAddr":"109.121.29.93","app":"files","message":"Can't write upload limit to \/tmp\/oc_tmp_cHudjl-folder\/.user.ini. Please check the file permissions","level":2,"time":"2017-01-29T10:36:48+00:00","method":"POST","url":"\/index.php","user":"oktogo","version":"11.0.1.2"}

Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
not installed
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
not installed
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
jquery-migrate.min.js?v=ff090e9…:2 JQMIGRATE: Migrate is installed, version 1.4.0
mail.min.js?v=ff090e9…:157 Starting Mail …
mail.min.js?v=ff090e9…:152 initializing cache…
mail.min.js?v=ff090e9…:148 [ui] "content:loading" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "notification:request" Array[0]
mail.min.js?v=ff090e9…:148 [account] "entities" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "sidebar:loading" Array[0]
mail.min.js?v=ff090e9…:148 [navigation] "setup" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "navigation:newmessage:show" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "sidebar:accounts" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "composer:leave" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "navigation:hide" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "setup:show" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [account] "create" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "navigation:show" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "content:loading" Array[0]
mail.min.js?v=ff090e9…:148 [account] "entities" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "sidebar:loading" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "search:set" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "content:loading" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "composer:leave" Array[0]
mail.min.js?v=ff090e9…:148 [folder] "setactive" Array[2]
mail.min.js?v=ff090e9…:148 [message] "entities" Array[3]
mail.min.js?v=ff090e9…:148 [folder] "setactive" Array[2]
mail.min.js?v=ff090e9…:148 [ui] "folder:changed" Array[0]
mail.min.js?v=ff090e9…:148 [navigation] "folder" Array[2]
mail.min.js?v=ff090e9…:148 [ui] "navigation:newmessage:show" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "sidebar:accounts" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "foldercontent:show" Array[3]
mail.min.js?v=ff090e9…:148 [ui] "title:update" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "messagesview:message:setactive" Array[1]
mail.min.js?v=ff090e9…:148 [message] "bodies" Array[3]
mail.min.js?v=ff090e9…:148 [message] "fetch:bodies" Array[3]
mail.min.js?v=ff090e9…:148 [ui] "composer:leave" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "message:loading" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "title:update" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "messagesview:message:setactive" Array[1]
mail.min.js?v=ff090e9…:148 [message] "entity" Array[3]
mail.min.js?v=ff090e9…:148 [message] "load" Array[3]
mail.min.js?v=ff090e9…:148 [ui] "composer:events:undelegate" Array[0]
mail.min.js?v=ff090e9…:148 [message] "flag" Array[5]
mail.min.js?v=ff090e9…:148 [ui] "messagesview:messageflag:set" Array[3]
mail.min.js?v=ff090e9…:148 [ui] "message:show" Array[1]
mail.min.js?v=ff090e9…:148 [notification] "favicon:change" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "composer:leave" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "title:update" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "messagesview:message:setactive" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "message:loading" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "title:update" Array[0]
mail.min.js?v=ff090e9…:148 [ui] "messagesview:message:setactive" Array[1]
mail.min.js?v=ff090e9…:148 [message] "entity" Array[3]
mail.min.js?v=ff090e9…:148 [message] "load" Array[4]
mail.min.js?v=ff090e9…:148 [ui] "composer:events:undelegate" Array[0]
mail.min.js?v=ff090e9…:148 [message] "flag" Array[5]
mail.min.js?v=ff090e9…:148 [ui] "messagesview:messageflag:set" Array[3]
mail.min.js?v=ff090e9…:148 [ui] "message:show" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [message] "draft" Array[3]
mail.min.js?v=ff090e9…:148 [message] "send" Array[3]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
mail.min.js?v=ff090e9…:148 [ui] "document:click" Array[1]
https://server/index.php/apps/mail/accounts/1/send Failed to load resource: the server responded with a status of 500 ()
mail.min.js?v=ff090e9…:148[notification] "favicon:change" Array[1]

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>
config.php
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxxxxx',
  'secret' => 'xxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'servername',
  ),
  'datadirectory' => '/var/www/vhosts/servername/data',
  'overwrite.cli.url' => 'https://servername',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => 'xxxxxxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'mail_from_address' => 'post@servername',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'servername',
  'mail_from_name' => 'My NextCloud',
  'knowledgebaseenabled' => false,
);
-----------------------------------------------------------------------------

**Comment by g4jsg** [comment]
@ChristophWurst  Any idea if this can be resolved?

Thanks
John

**Comment by ChristophWurst** [comment]
Hey,

it seems like the markdown syntax is messed up. Could you try to fix it and add all the information the templates asks for?

**Comment by g4jsg** [comment]
Thanks for getting back to me, however I'm unsure of what you meant.

You want me to try and fix it? What information in what template are you referring to please?

John

**Comment by ChristophWurst** [comment]
Hi,

sorry that I was not clear enough. Please see the [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md) and fill out all fields. Make sure you do *not* remove any of the quotes as they make sure code and logs are rendered correctly. Thanks

**Comment by g4jsg** [comment]
OK, let me see what I can do as I do not have root access to the server.

**Comment by g4jsg** [comment]
OK, I've updated the original template to now include everything I have access to.

Thanks
John

**Comment by ChristophWurst** [comment]
> Sending mail failed: Error when communicating with the server.

Could you maybe provide the contents of the SMTP log after the error occurs? See https://github.com/nextcloud/mail/#smtp-logging. After you've enabled it, try to reproduce the bug again. You should find the log in `data/horde_smtp.log`.

**Comment by g4jsg** [comment]
Adding...
'app.mail.imaplog.enabled' => true,
  'app.mail.smtplog.enabled' => true,
  'app.mail.imap.timeout' => 20,
  'app.mail.smtp.timeout' => 2,
  'app.mail.transport' => 'php-mail',
to the config.php file fixed the problem.

Sending now says "message sent", emails show in the sent items folder, and the emails arrive at the recipient end.

John

**Comment by ChristophWurst** [comment]
Interesting. You were only supposed to change the config to log SMTP errors, but great that it is working now. Is this a hosted environment? Maybe your provider blocks the outgoing SMTP connection somehow.

**Comment by g4jsg** [comment]
I tried it all one line at a time, so I might provide more info for you.

Yes, this is on a plesk hosting platform. However, I'm not aware of smtp blocking.

John

**Comment by MarcoVant** [comment]
Same here.
Using also Plesk, and after adding these lines to config, sending works, BUT!
as its sending via php mail, most emails get into spamfolder - and thats sad.

any idea?

**Comment by ChristophWurst** [comment]
Seems the original problem has been resolved. I'm closing this ticket now.

> and thats sad

May I ask you to file a new issue for this problem? Thanks 😄

**Comment by tavinus** [comment]
Hi, Sorry but I still have this problem on the current Nextcloud (12.0.4).
Always says Error, but still sends the e-mail.
Using the `php-mail` option makes it not work for me, `smtp-mail` works but shows the error message (and stays with the message open).

**Comment by ChristophWurst** [comment]
Please file a new ticket. Thanks.
