### ISSUE TITLE
Mails shown in Inbox are outdated/missing

### ISSUE THREAD

**Issue by nRaecheR** [nextcloud/mail#3049]
Hi all,

I've been using the Mail app since it's public release but sind the 1.3.0 update it is unusable for me. 

Here's the environment: 

- Nextcloud 18.04 (amd64, official Docker image)

- Mail 1.3.2

- Two Mail Accounts: 
  * One local IMAP account ("Admin")
  * One remote IMAP account ("Strato")

Here's the list of problems I'm encountering:

* The Strato account only shows the latest mail, one mail max. Sometimes it doesn't show any mail at all. This is the same for the account specific inbox and for the common inbox. And it seems that when I move a mail from the Inbox to another IMAP folder the mail seems to stay inside the Inbox in the Mail App. It won't recognize the move operation.
* The Admin account is very high traffic and this seems to be a problem too. It shows a lot of old mails that has been deleted from another mail program days ago. Trying to delete it once again from NC Mail app sometimes seem to lock the app up and I need to close the browser tab and reload it once again. The mails shown are never the mails that currently existing in the mail box. I can see mails from days ago that lived only some seconds and are deleted from it.

The main problem seems that the Mail App can't handle it when mails are deleted or moved from a another mail program.  The old version (-1.3.0) had problems with that too but a simple reloading of the Mail tab solved this, now this is permanent. A manual sync of the mail accounts won't help (occ mail sync command). 

The Mail App is totally unusable with my setup and needs some fixing to be working again. I can't see anything relevant in the log files. Please tell me how to help fix this problems.

**Comment by ChristophWurst** [comment]
> I can't see anything relevant in the log files.

I highly doubt this.

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log` and `data/horde_imap.log`.

**Comment by ChristophWurst** [comment]
Please use the bug report template for future reports: https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=

**Comment by spreeni151** [comment]
Dear Christoph,
I'm using NC Mail (18.04/1.3.4) on a NC turnkey system - I have no access to config files, just admin settings within NC. I noticed the same behavior as nRaecheR with a mail account of Strato.de. Mails of inbox are vanishing while a new one appears, although they are still stored on the server they are just not shown in the inbox. Similar behavior of 'sent mails' folder.
I checked back with an accout of another provider (all-inkl.de) and everything is fine here. So I think it has something to do with the communication to the server of some providers and it is not a general problem. 
I hope this helps a bit to enclose the problem - would it help to send a download of the errorlog in NC's settings panel?
BTW. Thanks for your work

**Comment by nRaecheR** [comment]
Thank you Christoph for your answer. Maybe you should configure the issue reporting that the template is used when someone is opening a new issue?

Anyway, I've produced some log files but I find it difficult to provide it to you because they contain a lot of private/sensitive information, at least the horde_imap.log. Is there any way to sanitize the log file before I can send it to you? Are there any entries I can grep out and send to you?

**Comment by ChristophWurst** [comment]
> Thank you Christoph for your answer. Maybe you should configure the issue reporting that the template is used when someone is opening a new issue?

It's not always necessary. And the more complex the template, the more people will ignore it just like it happened here.

**Comment by nRaecheR** [comment]
No answers to my log files questions?
Maybe the diagnose output helps, here it is for the "Strato" account:
```
IMAP capabilities:
- AUTH
- CHILDREN
- ENABLE
- I18NLEVEL
- ID
- IDLE
- IMAP4
- IMAP4REV1
- MOVE
- MULTIAPPEND
- NAMESPACE
- QUOTA
- SORT
- STATUS
- UIDPLUS
- UNSELECT
- WITHIN
- XLIST

Account has 42913 messages in 201 mailboxes
```
and here for the "Admin" account :
```
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR
- STARTTLS

Account has 7060 messages in 9 mailboxes
```

**Comment by ChristophWurst** [comment]
> No answers to my log files questions?

I'll answer. Just try to be a bit more patient. This is free community support. If you have a support contract with Nextcloud GmbH please reach out through the support system so we can prioritize this issue.

**Comment by nRaecheR** [comment]
No rush, thank you.

**Comment by barrydegraaff** [comment]
I have seen this issue as well, for now work-around that seem to work most of the time to update the folders is to click the Mark all as read option in the ... menu.

**Comment by ChristophWurst** [comment]
> update the folders is to click the Mark all as read option in the ... menu

I don't see why that would help. It will just set a flag on a few messages. I still can not reproduce the issue.

**Comment by nRaecheR** [comment]
It doesn't help on my setup. Another problem is that the content in "All inboxes" has nothing to do with the inboxes per account. The account one is empty for Admin account but the common one is showing a lot of (deleted) mails from it.

**Comment by j-insan3** [comment]
I have the same issue. Clicking mark all as read does not work for me. Also i noticed that when you click on the menu next to inbox it counts the mails in my inbox correctly  (9). However i see a lot more emails, also the removed mails are still there. 

In the log inside nextcloud i don't see any mail related erros, or do i need to enable more debugging error logging somewhere else?

**Comment by ChristophWurst** [comment]
There is LOTS of debugging options. But right now I have no clue where to look, so those might not help at all.

**Comment by j-insan3** [comment]
All i can see is this this in the console log from the browser when i click on a not existing mail:

```
[DEBUG] mail: Inboxes sync'ed in background Object { app: "mail", uid: "jurgen" }mail.js:229:225524
[DEBUG] mail: navigated to another message Object { app: "mail", uid: "jurgen", to: {…}, from: {…} }mail.js:229:225524
[DEBUG] mail: using cached value for envelope 1-SU5CT1g=-277 Object { app: "mail", uid: "jurgen" }mail.js:229:225524
[DEBUG] mail: envelope and message fetched Object { app: "mail", uid: "jurgen", envelope: {…}, essage: undefined }mail.js:229:225524
[INFO] mail: message could not be found Object { app: "mail", uid: "jurgen", messageUid: "1-SU5CT1g=-277", envelope: {…}, message: undefined }
```

**Comment by ChristophWurst** [comment]
If you are like REALLY curious, then you have to enable debug mode and loggin on the server. Remove the account. Then add it again.

The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by nRaecheR** [comment]
The problem still exists with Mail 1.35. Strato Inbox says "3 messages" but the view/reading pane at the right says "No messages in this folder". It seems that the logic behind that is borked. Mail recognizes the presence of the mails but won't display them. When a new mail arrives that single mail will be displayed until deleted. After that it takes hours (?) to recognize that the mail is no longer in the inbox. Then the mail box in empty once again, but it still says that there are 3 Messages in it (which is the truth).

**Comment by ChristophWurst** [comment]
Yeah, the sync mechanism has problems on your setups.

What you see in the sidebar is a direct query that goes to IMAP. If you see a mismatch there, it's totally meaningless in terms of the cache state of the app.

I have no idea how to remotely debug this. If someone sends me credentials to an IMAP account with this problem that I can set up and debug locally I might be able to gather more info.

**Comment by ChristophWurst** [comment]
What is your cron setting btw? What type of cron do you run? How often is it run? See the admin settings.

**Comment by nRaecheR** [comment]
I could create you an temporary account for one of my Strato domains. if you send me an email address where I can send you the login/password to. 
Cron is System Cron, it works without problems.

**Comment by ChristophWurst** [comment]
> Cron is System Cron, it works without problems.

How often is it run?

> if you send me an email address where I can send you the login/password to.

Send it to christoph at nextcloud com

**Comment by nRaecheR** [comment]
Will do that ASAP. Every 15 minutes.

**Comment by nRaecheR** [comment]
I've send you the login credentials as email.

**Comment by ChristophWurst** [comment]
Thanks a lot. I'll have a look when my time allows.

**Comment by ChristophWurst** [comment]
> Every 15 minutes.

Side note: we now recommend running it every 5min :)

**Comment by nRaecheR** [comment]
Ah okay, but I had problems in the past with a long running task (News app update) which took more than 5 minutes but I will try 5 minutes again.

**Comment by w1n5l0w** [comment]
I also experience missing displayed mails with a Strato mail account. Is there already a solution? Or are there still debug infos needed (if, which)?

**Comment by ChristophWurst** [comment]
You could give https://help.nextcloud.com/t/mail-v1-4-0-ready-for-testing/84227 a go or wait a few days until the official release. There is always the chance that we fixed some of the problems in the meantime.

**Comment by nRaecheR** [comment]
Updating the Mail app to version 1.4.0 did not fix the problems :(

**Comment by w1n5l0w** [comment]
The update seems to have fixed our issues with not displayed mails though. But in contrast to @nRaecheR we didn't experience the display of in other clients deleted mails, so there might be a different or multiple problems with his setup?

Anyway, thanks for your great work at this App and NC @ChristophWurst !

**Comment by nRaecheR** [comment]
I've used the new version 1.4.0 for a few days now. There are changes in the behavior for the local, admin account. The mails shown are not always up to date but I can remove them without problems when a mail is "not found". 
For the Strato account I can't see any changes. It won't show more than one e-mail and most of the time no mail at all is shown in the inbox. 
@ChristophWurst Did you have time to test the Strato problems with the mail account I've provided to you?

**Comment by ChristophWurst** [comment]
nope

**Comment by serioustk** [comment]
Hi together,
I just wanted to put a '+1' here as I experience the exact same Issues with mailboxes hosted at Strato.
the latest Update to Mail 1.4.1 doesn't make any difference in the behaviour.

A fix for this issue would be great. Please let me know if I can assist with any logs or further information.

**Comment by Orangenlimo** [comment]
Same problem here. 
Strato mailbox where some mails are missing in the nc mail app. Although they are visible in the strato webmail.
NC 19.0.1, mail 1.4.1

**Comment by zimmer-service** [comment]
hi all,

I have encoutered the same issue on Nextcloud 20.0.4 with Mail 1.7.2.

Thats why I have seted up the development environment on my Windows 10 with WSL2 and ubuntu 20.04.
Here is running Nextcloud 21.0.0 beta5 and Mail 1.8.0-alpha.2.
I cannot reproduce the issue here, so it seems to be fixed.

Are there any recent changes that addresses this problem?
Or any idea how we can prove that this is realy fixed?

kind regards,
silvio

**Comment by zimmer-service** [comment]
hi all,

here are two log files from today morning. Hope it helps.
[horde_imap_1.8.log](https://github.com/nextcloud/mail/files/5800970/horde_imap_1.8.log)
[horde_imap_1.7.log](https://github.com/nextcloud/mail/files/5800971/horde_imap_1.7.log)

kind regards,
silvio

**Comment by juliushaertl** [comment]
@ChristophWurst In case it might help for debugging i also encounter this on our cloud with my company account.

**Comment by zimmer-service** [comment]
Hello,

I have updated Mail to 1.8. Still the same problem. 
Sometimes new messages are not displayed and old messages suddenly disappear. 
The only solution for now is to enable debug mode and clear the local cache.

kind regards,
Silvio

**Comment by szaimen** [comment]
> enable debug mode and clear the local cache.

Do you have some steps how to do this in detail?

**Comment by zimmer-service** [comment]
@szaimen 
you have to add 
`'debug' => true`
to your nextcloud config.php.
After reloading the mail app, you can click on the three dots next to your INBOX. There will be a new menu entry for deleting the local cache.

**Comment by szaimen** [comment]
@zimmer-service thanks!

**Comment by ChristophWurst** [comment]
Looks like we finally found out why some messages didn't vanish from the Mail app: https://github.com/nextcloud/mail/pull/4542

**Comment by zimmersi** [comment]
hi @ChristophWurst 
thanks for your awesome work!
Is this fix already shipped with Mail 1.8.3?

btw: it is not only the problem that the messages are not vanishing. I have also the problem that messages that are still on the IMAP server suddenly disapearing. The only way to get them back is clearing the local cache.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/4544/commits/7b66e2ce17c51a7b49613246d7db563b04bc2a1a should be included in v1.8.3

> I have also the problem that messages that are still on the IMAP server suddenly disapearing. The only way to get them back is clearing the local cache.

Could you open a ticket about that? I've never head about this.

**Comment by nRaecheR** [comment]
I've tested 1.9.1 and the problem is fixed for the one account, the high traffic "admin" account. For the other account ("Strato") nothing seems to have changed, mails are disappearing after a short period of time and will never be displayed again.

**Comment by ChristophWurst** [comment]
> For the other account ("Strato") nothing seems to have changed, mails are disappearing after a short period of time and will never be displayed again.

Please run `occ mail:account:diagnose <id>` from the CLI and report a new bug. I think you have QRESYNC and those accounts are harder to fix retroactively.

**Comment by nRaecheR** [comment]
Here's the output of the diagnose call:
``` 
IMAP capabilities:
- AUTH
- CHILDREN
- ENABLE
- I18NLEVEL
- ID
- IDLE
- IMAP4
- IMAP4REV1
- MOVE
- MULTIAPPEND
- NAMESPACE
- QUOTA
- SORT
- STATUS
- UIDPLUS
- UNSELECT
- WITHIN
- XLIST
```

**Comment by nRaecheR** [comment]
The issue with the Strato account is still there with Nextcloud 21.0.1 and Mail 1.9.5

**Comment by zimmersi** [comment]
it is an issue with the horde imap client.
I have already created a [pull request](https://github.com/horde/Imap_Client/pull/11), but is still pending.

you can fix it manually by editing this file
.../nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php

then clear local cache in debug mode or recreate the mail account

**Comment by nRaecheR** [comment]
Thank you, indeed, this seems to fix the problem.

Is there a way to clean the local cache without enabling the debug mode on the server or recreate all the mail accounts? Maybe a purge of a database table like oc_mail_messages?

**Comment by ChristophWurst** [comment]
there is no such feature right now. don't purge your oc_mail_messages.

**Comment by sebagallo** [comment]
> 
> 
> it is an issue with the horde imap client.
> I have already created a [pull request](https://github.com/horde/Imap_Client/pull/11), but is still pending.
> 
> you can fix it manually by editing this file
> .../nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php
> 
> then clear local cache in debug mode or recreate the mail account

this has been merged upstream, can we get another release including this fix?

**Comment by ChristophWurst** [comment]
v1.10.0 will come in a few days. Sorry for the delay :v:

**Comment by nRaecheR** [comment]
Updating to v1.10.0 fixed the problems described in the initial post. Thank you all for your good work!

**Comment by szaimen** [comment]
I fear I still experience this on c.nc.c with my company mail account. :/
cc @st3iny and @miaulalala 145 mails shown in the mailbox in the mail app on c.nc.c and only 26 in thunderbird.

**Comment by st3iny** [comment]
> I fear I still experience this on c.nc.c with my company mail account. :/ cc @st3iny and @miaulalala 145 mails shown in the mailbox in the mail app on c.nc.c and only 26 in thunderbird.

Me too. From time to time there are mails in my inbox envelope list which I moved/deleted on another client. When clicking them the thread view will show no envelope body (just the subject, recipient etc.). It happens very rarely and I'm not able to reproduce it reliably.

**Comment by miaulalala** [comment]
Then I'd suggest reopening this issue so we have all the collected information :)

**Comment by devmarxx** [comment]
Same problem as in the first post here. NC 23.0.1, Mail 1.11.6, cyrus-impad 3.2.6-2+deb11u1 with "expunge_mode: immediate"

![no_mail](https://user-images.githubusercontent.com/15102171/151770940-cc3fe92b-fe15-4cb5-8246-792432ac7877.png)

occ mail:account:diagnose <id> 

IMAP capabilities:
- AUTH
- ENABLE
- ID
- IMAP4REV1
- LITERAL+
- SASL-IR

(???, is that all? i.e. XLIST is missing?)

When I clear the cache, everything is there. Next day the situation is as in the picture again.

Regards

Chris

**Comment by miaulalala** [comment]
> I've tested 1.9.1 and the problem is fixed for the one account, the high traffic "admin" account. For the other account ("Strato") nothing seems to have changed, mails are disappearing after a short period of time and will never be displayed again.

RIght, this reminds me of the issue we're currently having with iCloud acounts. I could be completely on the wrong track here, but I debugged this a while ago and one issue was the the "vanidshedUids" that were requested for comparing our local state to imap contained uids that were not vanished after all, thus leading to syncing and then immediately disappearing messages in the inbox:

https://github.com/nextcloud/mail/blob/0fc344ecd410ae9215c754a6640f285ddf46c9d6/lib/IMAP/Sync/Synchronizer.php#L71-L87

**Comment by devmarxx** [comment]
After the update to NC 23.0.1.2 yesterday I took a look in the "Overview" settings section. The system told me there I needed to set "opcache_interned_strings_buffer" larger than 8 (I set it to 10 then) and I had to perform a "occ db:add-missing-indices". 

After I did that I cleared the cache for my INBOX again and that went, in contrast to before, super fast (seconds instead of minutes). All mails are visible again in the INBOX. Let's see for how long, but there is new hope :-)

Regards

Chris

**Comment by devmarxx** [comment]
Nope, that was not the solution. Mails are not showing again ...

**Comment by devmarxx** [comment]
I'm now on NC 23.0.2 with Mail 1.11.7.

Problem remains ...

Regards

Chris

**Comment by devmarxx** [comment]
As there is no progress on this issue, and more importantly no communication on if anything is happening at all, I switched to the "rainloop" Nextcloud app.

The lag of communication is not inviting to participate in the development of Nextcloud and its apps.

Regards

Chris

**Comment by nRaecheR** [comment]
It's back....after update to version 1.12.0 (NC 23) the mails in the inbox are now outdated again.

**Comment by plantroon** [comment]
It is possible that the same thing happened to me with self-hosted Mailcow (uses Dovecot) - the state of the inbox displayed in Nextcloud mail app was outdated. All other IMAP/EAS clients displayed it correctly. I just straight up deleted the account and re-added it and now I have this:
![KGF](https://user-images.githubusercontent.com/9124099/180621318-dbd94dee-674a-44ca-9e1b-ba1f8856b76e.png)

Any chance @nRaecheR could reproduce this please?

Here are the logs from when viewing an e-mail with no subject and ? as sender:
```
------------------------------
>> Sat, 23 Jul 2022 20:17:08 +0000
>> Connection to: imap://mailcow.plantroon.com:993/
>> Server connection took 0.0124 seconds.
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: plantroon@plantroon.com)]
S: 1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk] Logged in
>> Command 1 took 0.0836 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 EXAMINE INBOX (QRESYNC (1628609455 69311 479:480,483,485:486,488,492:495,498:499,510,512:517,519:520,523,526:527,532,534:542,545,547,549,551,555,557,560:567,569:570,573:574,583:585,589:593,597:598,601:603,605:606,608,610,612,615:617,624:625,632:634,639,642:645,652,662,670:672,686,688,705:707,709:710,722:723,726,730:731,735,741,743:749,751,754:764,766,2922:2923,2926:2936,2941,3536,3919,4142,4232,4244,4431,4671,5722,6366,6768,6770,6789,6844,6892,7044,7047:7049,8392,9169,9374,9981,10076,10562,11932,12063,12640,12865,13170,13499:13501,14316,14833,15642,16936,17046,17543,18382,18920,20523,22905,23859,24744:24745,24803,24813,24815:24824))
S: * ENABLED QRESYNC
S: 2 OK Enabled (0.001 + 0.000 secs).
>> Command 2 took 0.0006 seconds.
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded NonJunk)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 193 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 184] First unseen.
S: * OK [UIDVALIDITY 1628609455] UIDs valid
S: * OK [UIDNEXT 24825] Predicted next UID
S: * OK [HIGHESTMODSEQ 69311] Highest
S: 3 OK [READ-ONLY] Examine completed (0.001 + 0.000 secs).
>> Command 3 took 0.0015 seconds.
C: 4 UID FETCH 23774 (ENVELOPE FLAGS INTERNALDATE BODY.PEEK[HEADER])
S: 4 OK Fetch completed (0.001 + 0.000 secs).
>> Command 4 took 0.0006 seconds.

==> data/nextcloud.log <==
{"reqId":"emALmoOJE5nduuY1spST","level":0,"time":"2022-07-23T20:17:09+00:00","remoteAddr":"172.31.0.1","user":"plantroon","app":"mail","method":"GET","url":"/apps/mail/api/messages/23296/body","message":"findByIds in INBOX got 1 UIDs (23774) and found 1. minFetched=23774 maxFetched=23774","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62","version":"24.0.3.2","data":{"app":"mail"}}

==> data/horde_imap.log <==
C: 5 UID FETCH 23774 (ENVELOPE BODYSTRUCTURE FLAGS RFC822.SIZE INTERNALDATE BODY.PEEK[HEADER])
S: 5 OK Fetch completed (0.001 + 0.000 secs).
>> Command 5 took 0.0008 seconds.
C: 6 LOGOUT
S: * BYE Logging out
S: 6 OK Logout completed (0.001 + 0.000 secs).
>> Command 6 took 0.0025 seconds.
------------------------------
>> Sat, 23 Jul 2022 20:17:11 +0000
>> Connection to: imap://mailcow.plantroon.com:993/
>> Server connection took 0.0133 seconds.
S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: plantroon@plantroon.com)]
S: 1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk] Logged in
>> Command 1 took 0.0848 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 SELECT INBOX (QRESYNC (1628609455 69311 479:480,483,485:486,488,492:495,498:499,510,512:517,519:520,523,526:527,532,534:542,545,547,549,551,555,557,560:567,569:570,573:574,583:585,589:593,597:598,601:603,605:606,608,610,612,615:617,624:625,632:634,639,642:645,652,662,670:672,686,688,705:707,709:710,722:723,726,730:731,735,741,743:749,751,754:764,766,2922:2923,2926:2936,2941,3536,3919,4142,4232,4244,4431,4671,5722,6366,6768,6770,6789,6844,6892,7044,7047:7049,8392,9169,9374,9981,10076,10562,11932,12063,12640,12865,13170,13499:13501,14316,14833,15642,16936,17046,17543,18382,18920,20523,22905,23859,24744:24745,24803,24813,24815:24824))
S: * ENABLED QRESYNC
S: 2 OK Enabled (0.001 + 0.000 secs).
>> Command 2 took 0.0007 seconds.
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded NonJunk)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded NonJunk \*)] Flags permitted.
S: * 193 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 184] First unseen.
S: * OK [UIDVALIDITY 1628609455] UIDs valid
S: * OK [UIDNEXT 24825] Predicted next UID
S: * OK [HIGHESTMODSEQ 69311] Highest
S: 3 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
>> Command 3 took 0.0018 seconds.
C: 4 UID STORE 23774 +FLAGS \seen
S: 4 OK Store completed (0.001 + 0.000 secs).
>> Command 4 took 0.0006 seconds.
C: 5 LOGOUT
S: * BYE Logging out
S: 5 OK Logout completed (0.001 + 0.000 secs).
>> Command 5 took 0.0007 seconds.
```

In the database the subjects are empty and in this write-out as well:
```
plantroon@liberty:/srv/vapps/nextcloud$ /usr/bin/docker exec -t -u www-data nextcloud-app-1 php -f occ mail:account:export-threads 1 | grep subj | tail -n30
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "",
        "subject": "Intel GuC Firmware Fix Submitted For Linux 5.19",
        "subject": "",
        "subject": "Keanu Reeves dropped by Comic-Con to reveal John Wick 4 sneak peek teaser",
        "subject": "Cron <plantroon@liberty> \/usr\/bin\/flock -x -n \/tmp\/rss2email.lock -c \"\/usr\/bin\/r2e run\"",
        "subject": "Security alert",
        "subject": "AMD Sensor Fusion Hub \"SFH1.1\" Support Coming In Linux 5.20 For Newer Laptops",
        "subject": "Seagate s\u013eubuje 30+ TB disk u\u017e o rok",
        "subject": "Problem: High CPU utilization (over 90% for 5m)",
        "subject": "Resolved in 15h 20m 0s: Zabbix agent is not available (for 3m)",
        "subject": "Resolved in 1m 9s: High CPU utilization (over 90% for 5m)",
        "subject": "Problem: Zabbix agent is not available (for 3m)",
```
All of the e-mails visible there were received AFTER adding the account to Nextcloud. And even out of those, one has the bug. The empty ones were already in the Inbox when adding the account.

Few more disclaimers:
- I have utf8mb4 correctly set up per documentation. I use the official docker image but I double-checked anyway. None of the e-mails contained any special characters anyway (emojis or anything similar)
- during sync, the web browser (Chrome and Edge, without extensions) is locked up for long periods of time on a machine with Core i7 9700k and 64 GB of RAM. I don't know what it's doing.

Is there any way to completely disable the cache in Mail app or would that hurt the performance too much? Or move it to Redis somehow?

**Comment by plantroon** [comment]
fyi v1.13.1 works .... it does not lock up the browser and it does not try to load the mailbox at once (it loads as I scroll...). If I find any more time, I'll continue testing towards newer versions as I don't know which one broke it. I also needed to drop the tables.

I am willing to provide login details on my mailcow instance to see if this can be reproduced. It is nothing out of the ordinary, just normal Dovecot. Contact me at any address at plantroon.com if any dev is willing to spend time on this.

**Comment by miaulalala** [comment]
Hey, thanks for  

> It is possible that the same thing happened to me with self-hosted Mailcow (uses Dovecot) - the state of the inbox displayed in Nextcloud mail app was outdated. All other IMAP/EAS clients displayed it correctly. I just straight up deleted the account and re-added it and now I have this: ![KGF](https://user-images.githubusercontent.com/9124099/180621318-dbd94dee-674a-44ca-9e1b-ba1f8856b76e.png)
> 
> Any chance @nRaecheR could reproduce this please?
> 
> Here are the logs from when viewing an e-mail with no subject and ? as sender:
> 
> ```
> ------------------------------
> >> Sat, 23 Jul 2022 20:17:08 +0000
> >> Connection to: imap://mailcow.plantroon.com:993/
> >> Server connection took 0.0124 seconds.
> S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
> C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: plantroon@plantroon.com)]
> S: 1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk] Logged in
> >> Command 1 took 0.0836 seconds.
> >> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
> C: 2 ENABLE QRESYNC
> C: 3 EXAMINE INBOX (QRESYNC (1628609455 69311 479:480,483,485:486,488,492:495,498:499,510,512:517,519:520,523,526:527,532,534:542,545,547,549,551,555,557,560:567,569:570,573:574,583:585,589:593,597:598,601:603,605:606,608,610,612,615:617,624:625,632:634,639,642:645,652,662,670:672,686,688,705:707,709:710,722:723,726,730:731,735,741,743:749,751,754:764,766,2922:2923,2926:2936,2941,3536,3919,4142,4232,4244,4431,4671,5722,6366,6768,6770,6789,6844,6892,7044,7047:7049,8392,9169,9374,9981,10076,10562,11932,12063,12640,12865,13170,13499:13501,14316,14833,15642,16936,17046,17543,18382,18920,20523,22905,23859,24744:24745,24803,24813,24815:24824))
> S: * ENABLED QRESYNC
> S: 2 OK Enabled (0.001 + 0.000 secs).
> >> Command 2 took 0.0006 seconds.
> S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded NonJunk)
> S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
> S: * 193 EXISTS
> S: * 0 RECENT
> S: * OK [UNSEEN 184] First unseen.
> S: * OK [UIDVALIDITY 1628609455] UIDs valid
> S: * OK [UIDNEXT 24825] Predicted next UID
> S: * OK [HIGHESTMODSEQ 69311] Highest
> S: 3 OK [READ-ONLY] Examine completed (0.001 + 0.000 secs).
> >> Command 3 took 0.0015 seconds.
> C: 4 UID FETCH 23774 (ENVELOPE FLAGS INTERNALDATE BODY.PEEK[HEADER])
> S: 4 OK Fetch completed (0.001 + 0.000 secs).
> >> Command 4 took 0.0006 seconds.
> 
> ==> data/nextcloud.log <==
> {"reqId":"emALmoOJE5nduuY1spST","level":0,"time":"2022-07-23T20:17:09+00:00","remoteAddr":"172.31.0.1","user":"plantroon","app":"mail","method":"GET","url":"/apps/mail/api/messages/23296/body","message":"findByIds in INBOX got 1 UIDs (23774) and found 1. minFetched=23774 maxFetched=23774","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62","version":"24.0.3.2","data":{"app":"mail"}}
> 
> ==> data/horde_imap.log <==
> C: 5 UID FETCH 23774 (ENVELOPE BODYSTRUCTURE FLAGS RFC822.SIZE INTERNALDATE BODY.PEEK[HEADER])
> S: 5 OK Fetch completed (0.001 + 0.000 secs).
> >> Command 5 took 0.0008 seconds.
> C: 6 LOGOUT
> S: * BYE Logging out
> S: 6 OK Logout completed (0.001 + 0.000 secs).
> >> Command 6 took 0.0025 seconds.
> ------------------------------
> >> Sat, 23 Jul 2022 20:17:11 +0000
> >> Connection to: imap://mailcow.plantroon.com:993/
> >> Server connection took 0.0133 seconds.
> S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
> C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: plantroon@plantroon.com)]
> S: 1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY METADATA SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk] Logged in
> >> Command 1 took 0.0848 seconds.
> >> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
> C: 2 ENABLE QRESYNC
> C: 3 SELECT INBOX (QRESYNC (1628609455 69311 479:480,483,485:486,488,492:495,498:499,510,512:517,519:520,523,526:527,532,534:542,545,547,549,551,555,557,560:567,569:570,573:574,583:585,589:593,597:598,601:603,605:606,608,610,612,615:617,624:625,632:634,639,642:645,652,662,670:672,686,688,705:707,709:710,722:723,726,730:731,735,741,743:749,751,754:764,766,2922:2923,2926:2936,2941,3536,3919,4142,4232,4244,4431,4671,5722,6366,6768,6770,6789,6844,6892,7044,7047:7049,8392,9169,9374,9981,10076,10562,11932,12063,12640,12865,13170,13499:13501,14316,14833,15642,16936,17046,17543,18382,18920,20523,22905,23859,24744:24745,24803,24813,24815:24824))
> S: * ENABLED QRESYNC
> S: 2 OK Enabled (0.001 + 0.000 secs).
> >> Command 2 took 0.0007 seconds.
> S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded NonJunk)
> S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft Old $Forwarded NonJunk \*)] Flags permitted.
> S: * 193 EXISTS
> S: * 0 RECENT
> S: * OK [UNSEEN 184] First unseen.
> S: * OK [UIDVALIDITY 1628609455] UIDs valid
> S: * OK [UIDNEXT 24825] Predicted next UID
> S: * OK [HIGHESTMODSEQ 69311] Highest
> S: 3 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
> >> Command 3 took 0.0018 seconds.
> C: 4 UID STORE 23774 +FLAGS \seen
> S: 4 OK Store completed (0.001 + 0.000 secs).
> >> Command 4 took 0.0006 seconds.
> C: 5 LOGOUT
> S: * BYE Logging out
> S: 5 OK Logout completed (0.001 + 0.000 secs).
> >> Command 5 took 0.0007 seconds.
> ```
> 
> In the database the subjects are empty and in this write-out as well:
> 
> ```
> plantroon@liberty:/srv/vapps/nextcloud$ /usr/bin/docker exec -t -u www-data nextcloud-app-1 php -f occ mail:account:export-threads 1 | grep subj | tail -n30
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "",
>         "subject": "Intel GuC Firmware Fix Submitted For Linux 5.19",
>         "subject": "",
>         "subject": "Keanu Reeves dropped by Comic-Con to reveal John Wick 4 sneak peek teaser",
>         "subject": "Cron <plantroon@liberty> \/usr\/bin\/flock -x -n \/tmp\/rss2email.lock -c \"\/usr\/bin\/r2e run\"",
>         "subject": "Security alert",
>         "subject": "AMD Sensor Fusion Hub \"SFH1.1\" Support Coming In Linux 5.20 For Newer Laptops",
>         "subject": "Seagate s\u013eubuje 30+ TB disk u\u017e o rok",
>         "subject": "Problem: High CPU utilization (over 90% for 5m)",
>         "subject": "Resolved in 15h 20m 0s: Zabbix agent is not available (for 3m)",
>         "subject": "Resolved in 1m 9s: High CPU utilization (over 90% for 5m)",
>         "subject": "Problem: Zabbix agent is not available (for 3m)",
> ```
> 
> All of the e-mails visible there were received AFTER adding the account to Nextcloud. And even out of those, one has the bug. The empty ones were already in the Inbox when adding the account.
> 
> Few more disclaimers:
> 
> * I have utf8mb4 correctly set up per documentation. I use the official docker image but I double-checked anyway. None of the e-mails contained any special characters anyway (emojis or anything similar)
> * during sync, the web browser (Chrome and Edge, without extensions) is locked up for long periods of time on a machine with Core i7 9700k and 64 GB of RAM. I don't know what it's doing.
> 
> Is there any way to completely disable the cache in Mail app or would that hurt the performance too much? Or move it to Redis somehow?

Hi, thanks for debugging this so thoroughly! I think this is a different issue you're seeing. Can you please open a new ticket?

**Comment by plantroon** [comment]
> > It is possible that the same thing happened to me with self-hosted Mailcow (uses Dovecot) - the state of the inbox displayed in Nextcloud mail app was outdated. A
> 
> Hi, thanks for debugging this so thoroughly! I think this is a different issue you're seeing. Can you please open a new ticket?

Sorry, you're probably right. I reported it under #6938

**Comment by nRaecheR** [comment]
FYI, there are no improvements with 0.13.8.

**Comment by ChristophWurst** [comment]
Label dropped because it was a duplicate of the attribute at https://github.com/orgs/nextcloud/projects/61. The priority does **not** change.

**Comment by devmarxx** [comment]
Problem still not solved

Nextcloud 25.0.1
Mail 2.1.1

Is there anything I can help you with getting this sorted?

The way groupware bugs are handled is not very advertising for Nextcloud ...

Regards

Chris

**Comment by st3iny** [comment]
> Problem still not solved
> 
> Nextcloud 25.0.1 Mail 2.1.1
> 
> Is there anything I can help you with getting this sorted?
> 
> The way groupware bugs are handled is not very advertising for Nextcloud ...
> 
> Regards
> 
> Chris

We are aware that the problem is not solved. That's why the ticket is still open.

Before randomly complaining about Nextcloud please ask yourself the following two questions:
1. Am I paying for using Nextcloud?
2. If not, can I expect the developers to fix my problems for free?

If you have experience with PHP, JS and Nextcloud you could try to debug the problem. If you find a somewhat reliable way to reproduce the issue, please let us know ASAP.

The first step in fixing bugs is to find ways to reproduce them. We already tried multiple times and didn't find a way to reproduce it reliably.

Of course, you are always welcome to fix stuff yourself and open a PR.

**Comment by nRaecheR** [comment]
The update to 25.0.1/Mail 2.1.1 is a mixed bag for me for this issue. One account seems to be fixed ("the high traffic one"), the other lags behind sometimes. I think the mailbox will be updated each time I delete/move a mail from it or a new one arrives. But I'm not sure about this. This could be the reason why the high traffic mailbox is now up to date while the low traffic one is outdated after I open the mail app the first time in the morning.

It seems to be much better with this version, thank you for your work!

**Comment by devmarxx** [comment]
> > Problem still not solved
> > Nextcloud 25.0.1 Mail 2.1.1
> > Is there anything I can help you with getting this sorted?
> > The way groupware bugs are handled is not very advertising for Nextcloud ...
> > Regards
> > Chris
> 
> We are aware that the problem is not solved. That's why the ticket is still open.
> 
> Before randomly complaining about Nextcloud please ask yourself the following two questions:
> 
> 1. Am I paying for using Nextcloud?
> 2. If not, can I expect the developers to fix my problems for free?
> 
> If you have experience with PHP, JS and Nextcloud you could try to debug the problem. If you find a somewhat reliable way to reproduce the issue, please let us know ASAP.
> 
> The first step in fixing bugs is to find ways to reproduce them. We already tried multiple times and didn't find a way to reproduce it reliably.
> 
> Of course, you are always welcome to fix stuff yourself and open a PR.

Your attitude is exactly what "I'm complaining about". 

You do your stuff open source, I'll do mine stuff open source. All for the good of open source. 

And if we can help each other fine. If not, also fine.

But being open source and begging for paying is not my world. Remembers me of a dead horse called Owncloud.

Sorry, but I'm into Owncloud / Nextcloud since 10 years. Large scale, small scale. More or less active over the years, but this kind of response is not inviting get more active for me.

Regards

Chris

**Comment by reno3131** [comment]
https://github.com/nextcloud/mail/issues/8223#issuecomment-1498801136 

Some logs from another issue whiere this issue il linked.

**Comment by flortsch** [comment]
Experiencing similar issues. As a temporary fix, I deleted all DB table entries of oc_mail_messages and oc_mail_mailboxes, and performed an occ mail:sync command to force refresh my mail account.

**Comment by devmarxx** [comment]
A few weeks ago I upgraded my server to Debian 12. With that upgrade my Cyrus server was upgraded to version 3.6 and I ran into this problem:

https://groups.google.com/g/linux.debian.bugs.dist/c/_X_HvkFqum4

I could correct the mailboxes by using "reconstruct" and after that the mail from the reconstructing date on stay visible in the Inbox of Nextcloud's Mail.

As those mailboxes all were all set up under Cyrus 2.x and then have been upgraded from version to version, perhaps this post gives a clue to the problem described here:

https://groups.google.com/g/linux.debian.bugs.dist/c/_X_HvkFqum4/m/qnsEqFzmBAAJ

Just guessing, but I'm glad it seems to be working now.

Regards

Chris

**Comment by ChristophWurst** [comment]
Due to inactivity I'm assuming these issues have also been fixed while working on https://github.com/nextcloud/mail/issues/8223.
