### ISSUE TITLE
Avatars without image (i.e. with a glyph) display "no glyph" instead of cyrillic letter

### ISSUE THREAD

**Issue by aol-nnov** [nextcloud/mail#3366]
### Expected behavior
If  avatar to the left of e-mail message does not have an image, sender's first letter is displayed in the avatar circle

### Actual behavior

However, if sender's name is cyrillic, a `no glyph` message is displayed.

<img width="75" alt="image" src="https://user-images.githubusercontent.com/43190/87327613-ee99fc00-c53c-11ea-8488-ed64069846b1.png">

There was a similar problem in a system-wide user's avatar, but it is already fixed.
<img width="223" alt="image" src="https://user-images.githubusercontent.com/43190/87328069-9e6f6980-c53d-11ea-8b58-1d883a0848f3.png">

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Zimbra

### Server configuration

official nextcloud docker image

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** Chrome 83.0.4103.116 (Official Build) (64-bit)

**Operating system:** MacOS

**Comment by StCyr** [comment]
I think this happens in nextcloud-vue: https://github.com/nextcloud/nextcloud-vue/issues/1406

**Comment by StCyr** [comment]
PR created: https://github.com/nextcloud/nextcloud-vue/pull/1407

**Comment by StCyr** [comment]
Fixed by https://github.com/nextcloud/nextcloud-vue/pull/1407

**Comment by aol-nnov** [comment]
@StCyr thanks for the fix!

However, it does not fix some of the glyphs... (it might be a caching issue, though...)

<img width="74" alt="image" src="https://user-images.githubusercontent.com/43190/102045024-1ab9f180-3de9-11eb-8dce-5a67bad14128.png">

**Comment by StCyr** [comment]
Are you still using Mail 1.4? 
I doubt it will be fixed there because it requires using a new version of the @nextcloud-vue component

**Comment by aol-nnov** [comment]
@StCyr yes, it's 1.4.2 here.

Please tell me, in what version approximately would it be fixed? Do I need to upgrade nextcloud to newer version, too?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/1407/commits/6075da8bf8fab8d45eeaba2f1659ee61b4c12124 was included in v2.8.0+ of the nextcloud-vue lib.
https://github.com/nextcloud/mail/commit/055ef9a800beb915f094b6a1da67d40b55d7ed8f brought the 2.8 into this repo. We released that with v1.6+.

So yes, you'll need Nextcloud 20 for the new Mail version.

**Comment by aol-nnov** [comment]
Oh, I see, @ChristophWurst ! Thanks for the clarification!
