### ISSUE TITLE
Context Menu of Inbox to small for long translations

### ISSUE THREAD

**Issue by benks-io** [nextcloud/mail#3990]
Text of the Inbox Menu protrudes beyond the box in German translation.

![grafik](https://user-images.githubusercontent.com/57667105/98101346-60060d80-1e92-11eb-89c9-5c65c736086f.png)

A character break is prevented, which must surely be the case elsewhere. Unfortunately it does not work here because the tooltip box is limited to 150px.

**Mail app version:** 1.5.1
**Operating system**: Debian Buster
**Nextcloud Version:** 20.0.1
**Browser:** Firefox 78.4.0 ESR
**Operating system Client:** Debian Buster

**Comment by ChristophWurst** [comment]
Possibly fixed with nc/vue 3.x but @GretaD wanna have a look? :)

**Comment by GretaD** [comment]
Yes, i can reproduce it with other languages also. We have changed the action-menu font, let see if its still a problem after that applies, if yes, then i will send a PR.

**Comment by GretaD** [comment]
possible fix https://github.com/nextcloud/nextcloud-vue/pull/1576

**Comment by GretaD** [comment]
fixed nextcloud/nextcloud-vue#1576
