### ISSUE TITLE
Sync fails due to iconv error on alpine linux

### ISSUE THREAD

**Issue by tfmm** [nextcloud/mail#3999]
### Expected behavior
Inbox loads with list of messages

### Actual behavior
Inbox or other folders never load, get a constant `Loading messages` message where message list should be. 

### Mail app

**Mail app version:** 1.6.0

**Mailserver or service:** custom IMAP from a server running Virtualmin

### Server configuration

**Operating system**: NC Docker Container from linuxserver.io - 

**Web server:** NC Docker Container from linuxserver.io - Nginx

**Database:** PostgreSQL

**PHP version:** 7.3.24

**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:** Chrome, Chromium, and Vivaldi, all latest versions

**Operating system:** Ubuntu 20.10 and Fedora 33

**Comment by ChristophWurst** [comment]
Check your nextcloud.log for errors

**Comment by tfmm** [comment]
Meant to mention, there are no errors in nextcloud.log or in the nextcloud logging interface.

**Comment by ChristophWurst** [comment]
Okay let's try it differently: please try the sync from the CLI with `occ mail:account:sync <id>`, the `<id>` can be discovered by looking into the `oc_mail_accounts` table.

**Comment by tfmm** [comment]
Ok, so getting an error with the manual sync: 

```
root@55623887849b:/config/www/nextcloud# sudo -u abc php occ mail:account:sync 6
[debug] Initial sync 6:INBOX - fetch all messages from IMAP took 2s

In ImapToDbSynchronizer.php line 235:
                                                                                                                           
  Sync failed for 6:INBOX: Return value of OCA\Mail\Address::getEmail() must be of the type string or null, bool returned  
                                                                                                                           

In Address.php line 78:
                                                                                                  
  Return value of OCA\Mail\Address::getEmail() must be of the type string or null, bool returned  
                                                                                                  

mail:account:sync [-f|--force] [--] <account-id>
```

Looking at the accounts table, everything appears to be proper data types.

**Comment by ChristophWurst** [comment]
it's because of https://github.com/nextcloud/mail/pull/4007. we just fixed that :) you can download a patch from https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/4007.patch

once applied the sync should work.

**Comment by tfmm** [comment]
Still getting the same errors after patching the file and restarting the docker container.  For good measure I also re-installed the mail app and re-patched, no change.

**Comment by ChristophWurst** [comment]
Ah, I remember another thing. `iconv` doesn't work on alpine apparently. I'm assuming that is the docker image you're using, right? See https://github.com/nextcloud/mail/issues/3908

**Comment by ChristophWurst** [comment]
https://stackoverflow.com/a/63747282/2239067 this is an issue on a larger scale. Which Docker image do you use? Is it the "offical" one for Nextcloud? Guess we should report this there …

**Comment by tfmm** [comment]
Aha! That appears it may be the issue. I'm using the linuxserver.io nextcloud image. I'll do some testing and if I can get a resolution working, will report there.  Thanks for the help.

**Comment by tfmm** [comment]
Opened a PR with linuxserver-docker-nextcloud to fix this. Thanks again for the troubleshooting.

**Comment by ChristophWurst** [comment]
Closing as this is out of scope for us but pinning so others can find it more easily.

**Comment by diademiemi** [comment]
Removing //IGNORE on this line fixes the issue for me, hope this can be a quick bandaid patch for others until it gets a permanent fix. 
https://github.com/nextcloud/mail/blob/9669b1bea81a6feb143a27aba85ff5c19d40a54d/lib/Address.php#L82

`		$utf8 = iconv("UTF-8", "UTF-8//IGNORE", $email);`
To
`		$utf8 = iconv("UTF-8", "UTF-8", $email);`

Instantly fixes it

**Comment by ChristophWurst** [comment]
This is not a fix. This is a hack.

The sole purpose of the iconv invokation is to throw away any characters that is are not valid utf8. You'll run into other, even nastier bugs later on because now your data gets polluted with incorrect utf8.
