### ISSUE TITLE
»to« and »cc« fields of replies not correctly filled anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#541]
Test with an email which is sent to you and another person, or has someone in cc too.

Probably regression of https://github.com/nextcloud/mail/pull/515

**Comment by ChristophWurst** [comment]
Please check out #551 and try to reproduce there. That PR should fix it as it's a general address handling overhaul. Thanks

**Comment by jancborchardt** [comment]
It’s not fully fixed. Try with an email like this:

Sent from Ali to Bob, yourself and Dani in cc

The reply field will have Ali in the to, the cc people in the cc again. But the original people from the »to«, whether it’s one or multiple, will not be in the »to« of the reply.

**Comment by ChristophWurst** [comment]
Please create a new ticket for this regression. Thanks!
