### ISSUE TITLE
Sub-sub-folders should be expandable and hyperlinks from subfolders which are collapsed are clickable

### ISSUE THREAD

**Issue by myzinsky** [nextcloud/mail#794]
### Steps to reproduce
1. Open Mail app

### Expected behaviour
All subfodlers and subsubfolders should be expandable.

### Actual behaviour
There are hyperlinks from subfolders which are collapsed that are clickable. Furthermore sub and subsub folders are not expandable they are shown as foo.bar or foo2.bar2.foo3 etc.

### Mail app

**Mail app version:** (see apps admin page)
0.7.10

**Mailserver or service:**
Courier

**Number of accounts:**
1

### Server configuration
**Operating system**:
Debain
**Web server:**
Apache 
**Database:**
Mysql
**PHP version:**
5
**Version:** (see admin page)

**Updated from an older version or fresh install:**
Updated
**List of activated apps:**
Mail, Contacts, Calendar

#### Client configuration
**Browser:**
Safari, Chome
**Operating system:**
Mac, Windows

##### Browser log
<details>
```
JQMIGRATE: Migrate is installed, version 1.4.0
build.js?v=bab260c7-4:91 Starting Mail …
DevTools failed to parse SourceMap: https://XXX/core/vendor/purify.min.js.map
build.js?v=bab260c7-4:24 GET https://XXX/index.php/apps/mail/api/avatars/url/SupportCenter%40ieee.org 404 (Not Found)
send @ build.js?v=bab260c7-4:24
ajax @ build.js?v=bab260c7-4:24
e @ build.js?v=bab260c7-4:162
n @ build.js?v=bab260c7-4:24
l._callHandler @ build.js?v=bab260c7-4:57
request @ build.js?v=bab260c7-4:57
_fetchAvatar @ build.js?v=bab260c7-4:138
onRender @ build.js?v=bab260c7-4:138
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
addChildView @ build.js?v=bab260c7-4:35
_addChild @ build.js?v=bab260c7-4:35
x.each.x.forEach @ build.js?v=bab260c7-4:24
_showCollection @ build.js?v=bab260c7-4:35
_renderChildren @ build.js?v=bab260c7-4:35
renderChildren @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
onRender @ build.js?v=bab260c7-4:101
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
showFolderContent @ build.js?v=bab260c7-4:98
y @ build.js?v=bab260c7-4:35
v @ build.js?v=bab260c7-4:35
d @ build.js?v=bab260c7-4:35
c.trigger @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
Promise resolved (async)
i @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:24
setTimeout (async)
x.delay @ build.js?v=bab260c7-4:24
O @ build.js?v=bab260c7-4:24
n @ build.js?v=bab260c7-4:24
(anonymous) @ build.js?v=bab260c7-4:57
s @ build.js?v=bab260c7-4:57
showFolder @ build.js?v=bab260c7-4:162
default @ build.js?v=bab260c7-4:162
execute @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
x.some.x.any @ build.js?v=bab260c7-4:24
loadUrl @ build.js?v=bab260c7-4:35
start @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
build.js?v=bab260c7-4:24 GET https://XXX/index.php/apps/mail/api/avatars/url/pfarramt.waldmohr%40evkirchepfalz.de 404 (Not Found)
send @ build.js?v=bab260c7-4:24
ajax @ build.js?v=bab260c7-4:24
e @ build.js?v=bab260c7-4:162
n @ build.js?v=bab260c7-4:24
l._callHandler @ build.js?v=bab260c7-4:57
request @ build.js?v=bab260c7-4:57
_fetchAvatar @ build.js?v=bab260c7-4:138
onRender @ build.js?v=bab260c7-4:138
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
addChildView @ build.js?v=bab260c7-4:35
_addChild @ build.js?v=bab260c7-4:35
x.each.x.forEach @ build.js?v=bab260c7-4:24
_showCollection @ build.js?v=bab260c7-4:35
_renderChildren @ build.js?v=bab260c7-4:35
renderChildren @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
onRender @ build.js?v=bab260c7-4:101
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
showFolderContent @ build.js?v=bab260c7-4:98
y @ build.js?v=bab260c7-4:35
v @ build.js?v=bab260c7-4:35
d @ build.js?v=bab260c7-4:35
c.trigger @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
Promise resolved (async)
i @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:24
setTimeout (async)
x.delay @ build.js?v=bab260c7-4:24
O @ build.js?v=bab260c7-4:24
n @ build.js?v=bab260c7-4:24
(anonymous) @ build.js?v=bab260c7-4:57
s @ build.js?v=bab260c7-4:57
showFolder @ build.js?v=bab260c7-4:162
default @ build.js?v=bab260c7-4:162
execute @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
x.some.x.any @ build.js?v=bab260c7-4:24
loadUrl @ build.js?v=bab260c7-4:35
start @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
build.js?v=bab260c7-4:24 GET https://XXX/index.php/apps/mail/api/avatars/url/mario.barbareschi%40unina.it 404 (Not Found)
send @ build.js?v=bab260c7-4:24
ajax @ build.js?v=bab260c7-4:24
e @ build.js?v=bab260c7-4:162
n @ build.js?v=bab260c7-4:24
l._callHandler @ build.js?v=bab260c7-4:57
request @ build.js?v=bab260c7-4:57
_fetchAvatar @ build.js?v=bab260c7-4:138
onRender @ build.js?v=bab260c7-4:138
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
addChildView @ build.js?v=bab260c7-4:35
_addChild @ build.js?v=bab260c7-4:35
x.each.x.forEach @ build.js?v=bab260c7-4:24
_showCollection @ build.js?v=bab260c7-4:35
_renderChildren @ build.js?v=bab260c7-4:35
renderChildren @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
onRender @ build.js?v=bab260c7-4:101
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
showFolderContent @ build.js?v=bab260c7-4:98
y @ build.js?v=bab260c7-4:35
v @ build.js?v=bab260c7-4:35
d @ build.js?v=bab260c7-4:35
c.trigger @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
Promise resolved (async)
i @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:24
setTimeout (async)
x.delay @ build.js?v=bab260c7-4:24
O @ build.js?v=bab260c7-4:24
n @ build.js?v=bab260c7-4:24
(anonymous) @ build.js?v=bab260c7-4:57
s @ build.js?v=bab260c7-4:57
showFolder @ build.js?v=bab260c7-4:162
default @ build.js?v=bab260c7-4:162
execute @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
x.some.x.any @ build.js?v=bab260c7-4:24
loadUrl @ build.js?v=bab260c7-4:35
start @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
build.js?v=bab260c7-4:24 GET https://XXX/index.php/apps/mail/api/avatars/url/iscas%40epapers.org 404 (Not Found)
send @ build.js?v=bab260c7-4:24
ajax @ build.js?v=bab260c7-4:24
e @ build.js?v=bab260c7-4:162
n @ build.js?v=bab260c7-4:24
l._callHandler @ build.js?v=bab260c7-4:57
request @ build.js?v=bab260c7-4:57
_fetchAvatar @ build.js?v=bab260c7-4:138
onRender @ build.js?v=bab260c7-4:138
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
addChildView @ build.js?v=bab260c7-4:35
_addChild @ build.js?v=bab260c7-4:35
x.each.x.forEach @ build.js?v=bab260c7-4:24
_showCollection @ build.js?v=bab260c7-4:35
_renderChildren @ build.js?v=bab260c7-4:35
renderChildren @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
onRender @ build.js?v=bab260c7-4:101
i @ build.js?v=bab260c7-4:35
triggerMethod @ build.js?v=bab260c7-4:35
render @ build.js?v=bab260c7-4:35
N @ build.js?v=bab260c7-4:35
show @ build.js?v=bab260c7-4:35
showChildView @ build.js?v=bab260c7-4:35
showFolderContent @ build.js?v=bab260c7-4:98
y @ build.js?v=bab260c7-4:35
v @ build.js?v=bab260c7-4:35
d @ build.js?v=bab260c7-4:35
c.trigger @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
Promise resolved (async)
i @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:57
(anonymous) @ build.js?v=bab260c7-4:24
setTimeout (async)
x.delay @ build.js?v=bab260c7-4:24
O @ build.js?v=bab260c7-4:24
n @ build.js?v=bab260c7-4:24
(anonymous) @ build.js?v=bab260c7-4:57
s @ build.js?v=bab260c7-4:57
showFolder @ build.js?v=bab260c7-4:162
default @ build.js?v=bab260c7-4:162
execute @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:35
x.some.x.any @ build.js?v=bab260c7-4:24
loadUrl @ build.js?v=bab260c7-4:35
start @ build.js?v=bab260c7-4:35
(anonymous) @ build.js?v=bab260c7-4:57
```
</details>

**Comment by ChristophWurst** [comment]
Please post a screenshot of how the folder structure looks in the mail app versus how it looks in other apps.

**Comment by myzinsky** [comment]
Sorry I have to correct, there are no folders missing! I was confused I will explain why in the following.

This is the state: at the bottom, where I marked it with the red dot, there are clickable links leading to the folders which are currently collapsed! Seams that there is something wrong with the CSS/JS behind collapsing and uncollapsing.

<img width="245" alt="bildschirmfoto 2018-02-21 um 10 31 39" src="https://user-images.githubusercontent.com/1970554/36472674-cc1aa99a-16f2-11e8-91fe-cb4f5fc58830.png">

This happens when I unfold a folder:

<img width="250" alt="bildschirmfoto 2018-02-21 um 10 35 03" src="https://user-images.githubusercontent.com/1970554/36472783-1eec3da0-16f3-11e8-8a4e-49483da6cd18.png">

**Comment by ChristophWurst** [comment]
> they are shown as foo.bar or foo2.bar2.foo3

Confirmed. This should actually not happen, so this is definitely something we have to look into. Note that we deliberately only show subfolders of the first level and not deeper. So bar2.foo3 inside foo2 would be expected.

**Comment by myzinsky** [comment]
> Note that we deliberately only show subfolders of the first level and not deeper. So bar2.foo3 inside foo2 would be expected.

But this is on the roadmap too?

**Comment by ChristophWurst** [comment]
No. Because it was decided to now show these as full tree but partly flattened tree.

**Comment by brrrrrrrt** [comment]
looks quite broken, especially interesting is what happens to the folder "Archive". it gets translated to "Archiv" with a nice icon, but the all the subfolders are all shown as INBOX.Archive.20XX

![bildschirmfoto von 2018-06-13 00-07-04](https://user-images.githubusercontent.com/4489013/41319962-fdac9c2c-6e9d-11e8-90b6-6027a0fc0948.png)

this is how roundcube renders the structure:
![bildschirmfoto von 2018-06-13 00-08-18](https://user-images.githubusercontent.com/4489013/41319966-0174d8b0-6e9e-11e8-9d76-92810615dd08.png)

**Comment by ChristophWurst** [comment]
@brrrrrrrt your issue is unrelated but should be reported as a separate issue since that should have been fixed by https://github.com/nextcloud/mail/pull/782 (assuming you're using the latest version of this app).

**Comment by brrrrrrrt** [comment]
here we go #947

**Comment by MexHigh** [comment]
Any progress on that? I still have the problem for my Archives.

**Comment by dehnhardt** [comment]
See: https://github.com/nextcloud/mail/pull/3147
