### ISSUE TITLE
Encoding issues with the preview of a message

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#8776]
### Steps to reproduce

1. Open mail app
2. Log in into an account
3. Check for an email that has characters like éô or similar
4. See how they show with a ? on the envelope list preview
5. the message is shown correctly on the body of the message

### Expected behavior

I can read the preview of a message when it has special characters

### Actual behavior

? is shown instead

### Mail app version

3.4.0-beta.3

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

![Screenshot from 2023-08-18 15-42-00](https://github.com/nextcloud/mail/assets/12728974/07db6a9c-e0b2-4ccd-b3a1-e41b6b86e898)

**Comment by hamza221** [comment]
Is it an é ? and if you open the message does it display correctly. and did you try on different browsers ?

**Comment by GretaD** [comment]
so far i can only reproduce it with french characters. I tried these other characters but looks good.

![Screenshot from 2023-08-18 17-39-05](https://github.com/nextcloud/mail/assets/12728974/bb31f396-ee94-43f9-8c8b-0ad1e0f3e3bf)


SO far i have tried FF and Brave browser

**Comment by GretaD** [comment]
#7222 maybe releated

**Comment by bjoernv** [comment]
Not all emails show this preview problem. One of my affected emails has two mime parts (text/plain + text/html) and the following encoding:

```
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
```

**Comment by bjoernv** [comment]
Here is an example email which shows incorrect umlauts (??? instead of äöü) in preview:
[encoding-sample.txt](https://github.com/nextcloud/mail/files/12431881/encoding-sample.txt)

![image](https://github.com/nextcloud/mail/assets/6728426/c90251da-77ad-4309-a339-cf96f48e14a8)

**Comment by SkyPunster** [comment]
I have same issue with preview and attachments.
![image](https://github.com/nextcloud/mail/assets/25499069/09bf19f5-cbff-42d8-836a-5abc4b46e852)
![image](https://github.com/nextcloud/mail/assets/25499069/b1f6dec6-34b7-4df6-89dc-e0aa5699b358)
![image](https://github.com/nextcloud/mail/assets/25499069/48ac9606-83b2-410c-9de1-5fd35632bbe5)

**Comment by ferdiga** [comment]
same here, but not a general issue, some are encoded correctly some not, and th Umlaut must be  in the first line(s) to be visible. the message itself is displayed correctly
<img width="259" alt="20231214 110402 Mail - Storage Share" src="https://github.com/nextcloud/mail/assets/6248560/89bf91b4-ba19-4a82-bca6-a02505d6633c">

**Comment by AutomCoding** [comment]
I have the exact same issue where it sometimes works correctly.

One example that works correctly:
```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64
```

This also works:
```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
	charset=utf-8
```

This does not work (non-ascii chars replaced by question marks):
```
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
```
Neither does this (escape sequence printed, eg. ö displays as `=C3=B3`):
```
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

**Comment by ChristophWurst** [comment]
This should be fixed with https://github.com/nextcloud/mail/pull/10442. Can you confirm?

**Comment by thstyl2000** [comment]
Sorry, I don't see any changes on v4.1.1......still the same problem with iso-8859-1.
