### ISSUE TITLE
Unable to open inbox: "Call to a member function getEmail() on null"

### ISSUE THREAD

**Issue by trendzetter** [nextcloud/mail#903]
### Steps to reproduce
Could be specific to the content on my mailbox, not sure yet. I will check if I can log on to the service providers webmail later. Right now I can't remember the password. Will update this issue when I can get to more details.
Update: Everything worked, reading and sending email until a few days ago suddenly the inbox couldn't open anymore. I can configure an empty mailbox that I have set up on my own server. It's just that I would like to access the email with my internet provider. I will look into the content of the mailbox tonight. I guess the reason must be something I received recently.

1. Log on to nextcloud
2. Click to mail icon

### Expected behaviour
Inbox opens

### Actual behaviour
"Cannot op inbox" (in my native language)

## Server configuration detail

**Operating system:** Linux 3.14.79-116 #1 SMP PREEMPT Tue Sep 26 01:19:06 BRT 2017 aarch64

**Webserver:** nginx/1.13.6 (fpm-fcgi)

**Database:** mysql 10.0.34

**PHP version:** 7.1.16-1+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 12

**Where did you install Nextcloud from:** From image by https://www.c-rieger.de/

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - apporder: 0.4.1
 - audioplayer: 2.3.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - contacts: 2.1.3
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - phonetrack: 0.2.7
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - spreed: 3.2.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - checksum
 - comments
 - encryption
 - federation
 - files_clipboard
 - files_downloadactivity
 - files_versions
 - firstrunwizard
 - keeweb
 - survey_client
 - systemtags
 - twofactor_totp
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "odroid64",
        "amazingthings.diskstation.me"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/odroid64",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "loglevel": 1,
    "logtimezone": "Europe\/Berlin",
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "log_rotate_size": 104857600,
    "cron_log": true,
    "filesystem_check_changes": 1,
    "quota_include_external_storage": false,
    "knowledgebaseenabled": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "maintenance": false,
    "theme": "",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1,
    "auth.bruteforce.protection.enabled": true,
    "trashbin_retention_obligation": "auto, 7",
    "skeletondirectory": "",
    "defaultapp": "apporder",
    "activity_expire_days": 14,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Operating system:** Linux & Windows

## Logs

Error: Call to a member function getEmail() on null

    /var/www/nextcloud/apps/mail/lib/Mailbox.php - line 205: OCA\Mail\Model\IMAPMessage->jsonSerialize()
    /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 129: OCA\Mail\Mailbox->getMessages('', NULL)
    [internal function] OCA\Mail\Controller\MessagesController->index(1, 'SU5CT1g=', NULL, '')
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 999: OC\Route\Router->match('/apps/mail/api/...')
    /var/www/nextcloud/index.php - line 37: OC handleRequest()
    {main}

Server log (data/nextcloud.log)
The server log is empty even with debugging enabled. Access rights seem to be ok.

IMAP log (data/horde_imap.log)
can not find the horde imap log.

SMTP log (data/horde_smtp.log)
can not find the horde smtp log.

**Comment by trendzetter** [comment]
I could get back in my inbox by deleting some emails. I can still try to figure out what is happening if I can get logfiles going. I added 'debug' => true to config.php but still no logfiles. There is a log in the backend and it works but it shows no specifics about the imap conversation. And hints?

**Comment by ChristophWurst** [comment]
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

Please **always** double check your logs for sensitive information. E.g. the IMAP logs may contain your login password as base64-encoded string. Remove this information before posting it here.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/mail/issues/765

**Comment by trendzetter** [comment]
@ChristophWurst I enabled debug but nextcloud.log is empty and imap and smtp log not present.

**Comment by trendzetter** [comment]
something seems not working to debug mode.

**Comment by ChristophWurst** [comment]
FYI https://github.com/nextcloud/mail/issues/765 was fixed in 0.8.0

**Comment by trendzetter** [comment]
Yesterday I applied the install of Mail 0.8.1. I can see some differences but I am still having an issue opening the folder that contains to problematic item (null mail?).
When I open that folder I am getting a message inviting me to file a bug. Unfortunately the link doesn't work when not logged on in Github. I am getting an error 500 on Github when not logged on. I just logged on and tried again. I will start to fill out the issue template.

**Comment by ChristophWurst** [comment]
> When I open that folder I am getting a message inviting me to file a bug.

Congrats :confetti_ball:, I think you're the first person who discovered this "feature".

> When I open that folder I am getting a message inviting me to file a bug. Unfortunately the link doesn't work when not logged on in Github. I am getting an error 500 on Github when not logged on. I just logged on and tried again. I will start to fill out the issue template.

I hadn't considered this. Thanks for this feedback!

**Comment by silverstance** [comment]
Same problem here. Have a null mail, cant open Inbox. 
Upgraded to 0.8.1 but still not loading.

When moved the problem-email from the inbox folder Mail 0.8.1 started working fine again. 

Maybe some help to fix the bug: This is from the "source of the email", (in the header):

> From: "System Administrator"
> To: me@memail.se

This is the text verbatim. My other email client report the sender as "System Administrator" (including the "-marks). 

The email in question is a returned Delivery failure-email from a server. So the "From-string" is not exactly NULL but Mail 0.8.1 reports it in the log as NULL. The "from-string" is just not a correct email-adress.

Could this info be of help fixing this bug?

**Comment by ChristophWurst** [comment]
@silverstance could you please file a new ticket for your bug? I'm not sure this is related to the issue above. Thanks!
